[workspace]
resolver = "2"
members = ["crates/wordink-core", "crates/wordink-wasm"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/duketopceo/WordInk"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
